### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by byelik** [andreamazz/UIView-draggable#13]
Hi, how I can rotate and drag view?
At the moment when I rotate view dragging is not working...

**Comment by andreamazz** [comment]
Hi @byelik 
I just tried in the demo project (I enabled the rotation in the latest commit) and seems to be working fine. Can you reproduce the issue in the demo project?

**Comment by byelik** [comment]
Yes, I can try it, and then I will let you know
Can you post your code for rotation of UIVIew, maybe I'm doing something wrong...

**Comment by andreamazz** [comment]
No code really, I just enabled the rotation. You can try the project in this [live demo](https://appetize.io/app/rey013220c4b9pex34kg1qaf84?device=iphone5s&scale=75&orientation=portrait&osVersion=9.1)

**Comment by byelik** [comment]
In live demo I can rotate Phone, but I need to rotate UIView 30 degrees, for example.

**Comment by byelik** [comment]
sorry, I mean view not UIVIew

**Comment by andreamazz** [comment]
Ah sorry, I misunderstood the question then. 
Yeah the rotation is not supported since the drag moves the center and frame of the view.

**Comment by byelik** [comment]
Do you plan to support rotation?

**Comment by andreamazz** [comment]
I doubt it, it would require a full rewrite for many reasons. Sorry about that.

**Comment by byelik** [comment]
It's to bad, thanks for your answers.
