### ISSUE TITLE
When included, this pod seems to mess with UIKit's general behaviors.

### ISSUE THREAD

**Issue by rsmoz** [andreamazz/UIView-draggable#14]
For example, UIImagePickerController is sometimes grayed-out or unresponsive, and UIActivityViewController, when presented, has its frame off the screen. I'll have to look for more details, but I know the issue is not present in my (older) fork: https://github.com/rsmoz/UIView-draggable

**Comment by andreamazz** [comment]
I just love breaking UIKit.  
I think I know why, I can revert a couple of versions, but that will break other things. I have an idea on how to rewrite part of the code to play nicer with autolayout and UIKit, though. I'll get back to you as soon as possible.

**Comment by jriskin** [comment]
1.0.1 Definitely created issues for me. Oddly, pushNavigationController became unresponsive. Reverted to 1.0.0 for now.

**Comment by asifalikhokhar** [comment]
yeah pushing controllers stopped working after installation, had to uninstall.
please fix

**Comment by andreamazz** [comment]
I reverted the changes in `1.0.2`. Let me know if that works for you.
