### ISSUE TITLE
using setDraggingStartedBlock setDraggingEndedBlock 

### ISSUE THREAD

**Issue by sundialsoft** [andreamazz/UIView-draggable#16]
1. I though it would be fun to alter the background color & alpha of view while they moved so I tried out these blocks but the views do not land on the X,Y coords I leave them on. They jump a little.
My Code is:
```objc
    __weak typeof(timerView) weakSelf = timerView;
    [timerView setDraggingStartedBlock:^
     {
         weakSelf.backgroundColor=switchColor;
         weakSelf.alpha = 0.9f;
     }];
    [timerView setDraggingEndedBlock:^
     {
         weakSelf.backgroundColor=[UIColor whiteColor];;
         weakSelf.alpha = 1.0f;
     }];
```
Without these blocks the views stop in the correct place. Is there something I can do to resolve this?
It's the EndedBlock that's the issue. Even an empty block caused the view to just at the end.

Not mission critical, just nice to try out the code.

**Comment by andreamazz** [comment]
This is probably related to #12 
When a layout cycle kicks in, the view is moved away. I need to implement the dragging in another way once I get the time to work on it :/

**Comment by sundialsoft** [comment]
Thanks for the feedback. My app is finished so after Christmas I will have time to look at this. I need to implement scroll view scrolling when a draggable view is moved out of the visible screen. I have code which does this in another app so will see if I can make it work here.

You are of course mentioned in the acknowledgements in my app 'Mama's Kitchen Timer' which should be off to Apple by tomorrow so live in 2 to 3 weeks from now I expect. 

All the best for the festive season

Ian
Aka sundialSoft

**Comment by andreamazz** [comment]
That's great, happy to hear that. I'll keep you posted :+1:

**Comment by ricozinn** [comment]
Hey, I was seeing this problem too, and commenting out this line here seems to fix it:
```
if (sender.state == UIGestureRecognizerStateEnded && self.draggingEndedBlock) {
//commenting this out fixes it
//        self.layer.anchorPoint = CGPointMake(0.5, 0.5);
        self.draggingEndedBlock(self);
}
```

**Comment by andreamazz** [comment]
Correct, see #23
