### ISSUE TITLE
x,y should separate judgment

### ISSUE THREAD

**Issue by azureplus** [andreamazz/UIView-draggable#21]
if (newXOrigin <= cagingAreaOriginX ||
            newXOrigin + CGRectGetWidth(self.frame) >= cagingAreaRightSide ) {
            newXOrigin = CGRectGetMinX(self.frame);
         
        }
        if(newYOrigin <= cagingAreaOriginY ||
           newYOrigin + CGRectGetHeight(self.frame) >= cagingAreaBottomSide)
        {
                        newYOrigin = CGRectGetMinY(self.frame);
        }

**Comment by andreamazz** [comment]
Good point. Fixed in `1.0.4`
