### ISSUE TITLE
Resetting anchor point 

### ISSUE THREAD

**Issue by renjithn** [andreamazz/UIView-draggable#23]
`if (sender.state == UIGestureRecognizerStateEnded && self.draggingEndedBlock) {
        self.layer.anchorPoint = CGPointMake(0.5, 0.5);
        self.draggingEndedBlock(self);
    }`

Just wondering why one would need to have the drag end block implemented to have the anchor point reset.

**Comment by andreamazz** [comment]
Yeah, makes no sense. I guess it was a leftover piece of code.
 Thanks for catching this 👍

**Comment by renjithn** [comment]
Thanks for the quick response. :) .`Just a follow up on this. I was also wondering why you need to set the anchor point in the gesture recogniser callback given that you are already setting the "center"

**Comment by andreamazz** [comment]
It's done to account for the x and y distance of the touch from the center. COmmenting that out will result in the view's center jumping under the user's finger.
