### ISSUE TITLE
move outside parent

### ISSUE THREAD

**Issue by mrhaxic** [andreamazz/UIView-draggable#28]
Hi, could the object move/drag outside of its parent ?

let's say uibutton added as subview in uiscrollview and I want to make the uibutton draggable in whole self.view not only inside uiscrollview

any hint?

**Comment by andreamazz** [comment]
Maybe using the `cagingArea`
something like:
view.cagingArea = CGRectMake(-parentOrigin.x, -parentOrigin.y, someSize, someSize)
