### ISSUE TITLE
How to use draggingEndedBlock to know that uiview has been ended dragging?

### ISSUE THREAD

**Issue by ZhuQinglei** [andreamazz/UIView-draggable#33]
@andreamazz I tried to override the variable draggingStartedBlock, draggingEndedBlock with didSet in order to know when the event is fired and call a function afterwards. However, I could not figure out how I can get the notification from  draggingEndedBlock and seems it is never called when I test. and the delegate function is never called as well.

would be much appreciated if you could provide examples on how to use these variables

Here is my code:
```
 override var draggingEndedBlock: ((UIView?) -> Void)!{
        didSet{
            print("drag ended")
            delegate?.updatePosition(self.frame, messageId: (self.message?.id)!)
        }
    }
```
Anyone could help?

**Comment by andreamazz** [comment]
???  
Why don't you just set the block?
```swift
yourView.draggingEndedblock = { [weak self] view in
  // do whatever
}
```
This is called when the drag gesture is done.

**Comment by ZhuQinglei** [comment]
@andreamazz  Thank you very much for the quick response! I did not know that I could do this..

Here is my code:  I am subclassing UIView, and self is a subclass of UIView, I wanted to delegate back the self frame to its superview
```
self.draggingEndedBlock = { (self) -> Void in
       delegate!.updatePosition(self.frame, messageId: (self.message?.id)!)
}
```
I am writing the code in swift and it is giving me error "Type of expression is ambigious without more context", do you know why is the case?

**Comment by andreamazz** [comment]
Don't call `self` the closure parameter
```swift
self.draggingEndedblock = { [weak self] view in
  guard let `self` = self  else { return }
  delegate!.updatePosition(self.frame, messageId: (self.message?.id)!)
}
```

I don't see why you need to subclass and add a delegate though, you can do that directly from the superview:
```swift
theDraggableView.draggingEndedblock = { [weak self] view in
  guard let `self` = self  else { return }
  self.updatePosition(view.frame, messageId: (view.message?.id)!)
}
```

**Comment by ZhuQinglei** [comment]
@andreamazz  Thank you soooooo much for the help, yes you are right, Actually I should directly call it in superview. Thank you so much!
