### ISSUE TITLE
How to drag a button without calling button action?

### ISSUE THREAD

**Issue by zkfpk6** [andreamazz/UIView-draggable#35]
When i stop drag a button, the button's action will called, i tryed this:
`
[self.roundButtonShadowView setDraggingStartedBlock:^(UIView *view) {
        @strongify(self)
        self.roundButton.userInteractionEnabled = NO;
    }];
    [self.roundButtonShadowView setDraggingEndedBlock:^(UIView *view) {
        @strongify(self)
        self.roundButton.userInteractionEnabled = YES;
    }];
`
but now worked, the button's action is still be called...
 Sorry for my bad English.

**Comment by andreamazz** [comment]
Hey @zkfpk6 
try to call `touchesCancelled` on your button in the drag start.

**Comment by zkfpk6** [comment]
> Hey @zkfpk6
> try to call `touchesCancelled` on your button in the drag start.

thank you, i already fix this, just use UITapGestureRecognizer instead of UIButton, works perfect.

**Comment by andreamazz** [comment]
Great
